spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/smuk
      username: smuk
      password: smuk
      hikari:
        connection-timeout: 20000
        maximum-pool-size: 5
        auto-commit: false
    jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
    liquibase:
      change-log: classpath:/liquibase/master.xml
    security:
      oauth2:
        resourceserver:
          jwt:
            public-key-location: classpath:/keys/smuk-pkey.pem
#logging:
#  level:
#    org:
#      springframework: DEBUG
